# -*- coding: utf-8 -*-
"""Python Exercícios Operações Matemáticas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMi12cfdRen1gkol2lMr0DvYidHK_S9W

# Exercício 1

Ler dois números inteiros, executar e mostrar o resultado das seguintes operações: adição, subtração, multiplicação e divisão
"""

numero1 = int(input('Digite o primeiro número: '))
numero2 = int(input('Digite o segundo número: '))

print(numero1, numero2)

adicao = numero1 + numero2
subtracao = numero1 - numero2
multiplicacao = numero1 * numero2
divisao = numero1 / numero2

print('Adição: ', adicao)
print('Subtração: ', subtracao)
print('Multiplicação: ', multiplicacao)
print('Divisão: ', round(divisao, 2))

"""# Exercício 2

Efetuar o cálculo da quantidade de litros de combustível gasto em uma viagem, utilizando um automóvel que faz 12 Km por litro. Para obter o cálculo, o usuário deve fornecer o tempo gasto na viagem e a velocidade média durante ela. Desta forma, será possível obter a distância percorrida com a fórmula DISTANCIA = TEMPO * VELOCIDADE. Tendo o valor da distância, basta calcular a quantidade de litros de combustível utilizada na viagem, com a fórmula: LITROS_USADOS = DISTANCIA / 12. O programa deve apresentar os valores da velocidade média, tempo gasto na viagem, a distância percorrida e a quantidade de litros utilizada na viagem
"""

tempo = float(input('Digite o tempo gasto na viagem: '))
velocidade = float(input('Digite a velocidade média: '))

print(tempo, velocidade)

distancia = tempo * velocidade
litros_usados = distancia / 12

print('Velocidade média: ', velocidade)
print('Tempo gasto na viagem: ', tempo)
print('Distância percorrida:', distancia)
print('Quantidade de litros:', round(litros_usados,1))